### ISSUE TITLE
Matrix not clearing after error resolves

### ISSUE THREAD

**Issue by ajbowler** [MLB-LED-Scoreboard/mlb-led-scoreboard#122]
After an error resolves, it stays on the screen until the next refresh, causing some funny displays on the scoreboard. Need to have the matrix refill after the error resolves.

**Comment by ajbowler** [comment]
@swemoney with the new game rendering loop, is this still an issue?

**Comment by swemoney** [comment]
Currently, the new rendering loop doesn't render the errors to the screen, just stdout.
