### ISSUE TITLE
Request update to rgbmatrixlib for more led-multiplexing options

### ISSUE THREAD

**Issue by phonorad** [MLB-LED-Scoreboard/mlb-led-scoreboard#144]
Thanks for your previous update to add led-multiplexing=4.  My panels almost work but not quite.  zheller has just release a new update to add multiplexing options up to 8 (I need option 8 for my panels).  Would it be possible to update the mlb scoreboard program to accept the new led-multiplexing options so I can try to get these oddball panels working?

**Comment by ajbowler** [comment]
Sure thing, I'll get this in the next release which should come pretty soon

**Comment by phonorad** [comment]
I got it working!!! Did a manual install of the new hzeller rgbmatrix drivers, then modified the utils.py to accept up to 8, and the led-multiplexing=8 works great! I now have a 64x32 display made of four 32x16 p8 modules showing the Tampa/Boston score.  Thanks for including the new mux options in the next release, so I will be able to keep up with other enhancements without jumping through hoops.  And I am starting to learn python as an added bonus!
