### ISSUE TITLE
Index out of bounds crash on refresh

### ISSUE THREAD

**Issue by swemoney** [MLB-LED-Scoreboard/mlb-led-scoreboard#170]
```May 19 18:04:53 raspberrypi python[445]: Traceback (most recent call last):
May 19 18:04:53 raspberrypi python[445]:   File "main.py", line 63, in <module>
May 19 18:04:53 raspberrypi python[445]:     MainRenderer(matrix, data).render()
May 19 18:04:53 raspberrypi python[445]:   File "/home/pi/mlb-led-scoreboard/renderers/main.py", line 74, in render
May 19 18:04:53 raspberrypi python[445]:     self.data.refresh_overview()
May 19 18:04:53 raspberrypi python[445]:   File "/home/pi/mlb-led-scoreboard/data/data.py", line 94, in refresh_overview
May 19 18:04:53 raspberrypi python[445]:     self.overview = mlbgame.overview(self.current_game().game_id)
May 19 18:04:53 raspberrypi python[445]:   File "/home/pi/mlb-led-scoreboard/data/data.py", line 137, in current_game
May 19 18:04:53 raspberrypi python[445]:     return self.games[self.current_game_index]
May 19 18:04:53 raspberrypi python[445]: IndexError: list index out of range
```

This crash happened during a refresh of the games list. When the script rebooted, it booted into standings mode. My best guess about what happened is mlb had an issue returning games (or maybe even my internet went down?) and the issue was still there when the scoreboard reloaded which caused it to go into off day mode.

This probably won't happen very often and a restart of the scoreboard fixed the issue but we might want to do a little more to recover from an error like this (like retrying in a couple of minutes) and start displaying scores again if we find games this time.

**Comment by twfarley** [comment]
Doesn't sound like this is an issue with the latest refactor.
