### ISSUE TITLE
Consume MLBGame v3

### ISSUE THREAD

**Issue by ajbowler** [MLB-LED-Scoreboard/mlb-led-scoreboard#18]
Work is underway to upgrade mlbgame to use the new MLB Stats API instead of the existing XML files. Once this is done, the scoreboard will need to consume the new changes.

**Comment by trevor-viljoen** [comment]
I've moved this work to https://github.com/trevor-viljoen/mlbapi

**Comment by twfarley** [comment]
Moving away from mlbgame
