### ISSUE TITLE
LED matrix only showing one color

### ISSUE THREAD

**Issue by ckomlos** [MLB-LED-Scoreboard/mlb-led-scoreboard#180]
When I go to run the actual scoreboard program the LED matrix only lights up one color. I have run the python sample programs and those show all three colors but the real program only lights up the red channel. 

Like this:![img_2312](https://user-images.githubusercontent.com/26513509/41696764-9e200b76-74ca-11e8-8eed-7b35dec86cab.JPG)

This is the graphics.py sample: 
![img_2313](https://user-images.githubusercontent.com/26513509/41696843-fdd9bfc6-74ca-11e8-8a81-b87c68dbea9f.JPG)

The code I am running is: `sudo python main.py --led-gpio-mapping=adafruit-hat --led-slowdown-gpio=2`

This is the config file I have: 
[config.json.txt](https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/files/2121952/config.json.txt)

**Comment by ckomlos** [comment]
This is the matrix I am using:  https://www.aliexpress.com/item/High-Refresh-Rate-Indoor-P6-RGB-SMD3528-Full-Color-32x32-Pixels-LED-Module-192x192mm-for-P6/32763763208.html?spm=a2g0s.9042311.0.0.40694c4dPUdfPH

**Comment by ckomlos** [comment]
Underside of the board

![img_2317](https://user-images.githubusercontent.com/26513509/41749130-17c69d44-7572-11e8-99c0-1cef50e03215.JPG)
![img_2316](https://user-images.githubusercontent.com/26513509/41749132-17e810aa-7572-11e8-964f-14e47fea8c0a.JPG)

**Comment by ajbowler** [comment]
I will reach out to the rgbmatrix maintainer and see if there's anything at the library level we can account for here.

**Comment by ajbowler** [comment]
Most of the discussions have been in Slack, the `--led-pwm-bits` command appears to be having some effect here. Will need to keep playing around and see what options this specific board needs to display correctly.
