### ISSUE TITLE
Updating the scoreboard for a Live game at a specified interval

### ISSUE THREAD

**Issue by broder22** [MLB-LED-Scoreboard/mlb-led-scoreboard#202]
Possibly add a configuration option to update stats for a live game every x seconds while that game is being displayed. This would allow live games to be up to date while being displayed for longer periods of time before rotating.

**Comment by ajbowler** [comment]
This is tricky to make sense of in terms of config schema...maybe have a new flag `update_interval` that is only used for live games. If we're gonna allow an arbitrary number of seconds for updating then we need validation to make sure it doesn't go over the rotation rate config for live games.

**Comment by twfarley** [comment]
This updates pretty regularly during a live game.
