### ISSUE TITLE
Run demo in off season

### ISSUE THREAD

**Issue by jmorim** [MLB-LED-Scoreboard/mlb-led-scoreboard#204]
Giving this as a Christmas gift. I'd like to try to throw something together that will demo a previous game instead of just showing the standings

**Comment by ajbowler** [comment]
Currently this would require you to change one line of code: https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/blob/master/data/data.py#L47

Change `datetime.today()` to `datetime(year, month, day)` and that will hardcode the scoreboard to whatever game(s) you want to display for that date.

**Comment by jmorim** [comment]
Cool, sounds easy enough, will try when I get home.
