### ISSUE TITLE
Ticker for other sports

### ISSUE THREAD

**Issue by PHI34Halladay** [MLB-LED-Scoreboard/mlb-led-scoreboard#209]
Hey guys,
I'm absolutely flashed by your ticker and already ordered the stuff I need to build one for my man cave.

Did you make those tickers for other sports (NFL, NBA, NHL, College) too? I'd absolutely love to have a ticker for each league on my wall :)

Hope to hear from you.

Regards,
Patrick

**Comment by ajbowler** [comment]
We currently only have MLB. If someone's interested in making one suited for other sports they can certainly have at it!
