### ISSUE TITLE
Games List

### ISSUE THREAD

**Issue by PHI34Halladay** [MLB-LED-Scoreboard/mlb-led-scoreboard#214]
Hey guys.

I want to build this thing for my own now and I was just wondering if it can only show one game a day or if the scoreboard scrolles through every game that is played that day? 

Thanks,
Patrick

**Comment by swemoney** [comment]
There are many options available for how games cycle. You can find more information in the configuration section of the `README` but to answer your question, it is not limited to showing just a single game per day.
