### ISSUE TITLE
Option in config.json to choose either 12H or 24H 

### ISSUE THREAD

**Issue by ohjk** [MLB-LED-Scoreboard/mlb-led-scoreboard#244]
Add a config.json option to choose between using 12H or 24H time globally

**Comment by ajbowler** [comment]
`time_format: "12H"` or `time_format: "24H"` as a root-level config option.

**Comment by ajbowler** [comment]
Done in dev. Will go out with next minor release

**Comment by ajbowler** [comment]
Closed by #253
