### ISSUE TITLE
v3.2.0 layout looks shifted for away team

### ISSUE THREAD

**Issue by pjwarner** [MLB-LED-Scoreboard/mlb-led-scoreboard#248]
![image](https://user-images.githubusercontent.com/69910/54725560-8bad7600-4b3d-11e9-891c-ce01346a4787.png)

**Comment by pjwarner** [comment]
Using 63x32 matrix board btw

Command to run the board
_sudo python main.py --led-cols 64 --led-gpio-mapping="adafruit-hat-pw\
m" --led-slowdown-gpio 3_

**Comment by twfarley** [comment]
That's only for the Orioles since their accent color is orange. Feel free to change it in ledcolors/teams.json
