### ISSUE TITLE
Add weather only display as a root level config option

### ISSUE THREAD

**Issue by ohjk** [MLB-LED-Scoreboard/mlb-led-scoreboard#251]
Add Config.json option to have scoreboard display only the weather screen

**Comment by swemoney** [comment]
This is already available via the `"news_ticker"`, `"always_display"` option in the config. We don't currently have any weather screen without news. There are probably other weather only projects if you aren't looking for the news screen at all.

**Comment by ohjk** [comment]
thanks, didnt realize that config would do what i was looking for!
