### ISSUE TITLE
Speed up text scrolling speed

### ISSUE THREAD

**Issue by hubster1000** [MLB-LED-Scoreboard/mlb-led-scoreboard#254]
Fastest scrolling speed (4) still feels too slow. Is it possible to speed this up?

**Comment by ajbowler** [comment]
We could certainly try extending the range. At some point you're going to get diminishing returns, based on the performance of your Pi. The faster it gets, the more times your board has to redraw itself to reposition the text

**Comment by ajbowler** [comment]
```
SCROLLING_SPEEDS = [0.3, 0.2, 0.1, 0.075, 0.05]
```

This is what we have right now. If 0.05 is too slow for you we could try adding 0.01 as a 5th option and see if that works out. The board may not be fast enough to work with that, though.

**Comment by davidjmorin** [comment]
has this been implemented yet?  The speed is terribly slow on pi zero

**Comment by ajbowler** [comment]
See the above pull request ^ it's on the latest release so make sure you have the latest.

Pi Zero is not a fast computer. It has far less resources than the other Pis so some extra chug is likely going to happen.
