### ISSUE TITLE
Scoreboard switching to wrong game

### ISSUE THREAD

**Issue by pitchforkninja** [MLB-LED-Scoreboard/mlb-led-scoreboard#259]
Scoreboard switches game to teams not in preferred list. Rotation is disabled, and only one team is in my config. 
[config.zip](https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/files/3027335/config.zip)
Scoreboard continues to work after switching. Debug journal displays this, error always happens after "Updating games for Today's Date"
![MLBerror](https://user-images.githubusercontent.com/48864030/55297154-c2f70f00-53e8-11e9-83c0-680bd42f8ca9.PNG)

**Comment by twfarley** [comment]
This shouldn't be a problem with the latest version.
