### ISSUE TITLE
128x64 Error Message

### ISSUE THREAD

**Issue by PHI34Halladay** [MLB-LED-Scoreboard/mlb-led-scoreboard#268]
After trying out the scoreboard with two LEDs did I decide to run it using four LEDs.
So I went out and bought two extra 64x32 LED panels.

When I want to run the scoreboard I get this error message:
![image](https://user-images.githubusercontent.com/46962608/56850856-81368700-6908-11e9-835a-0022e68f875f.png)

I used the w128h64.json and  edited the utils to that:
![image](https://user-images.githubusercontent.com/46962608/56851028-ad530780-690a-11e9-808e-7ff9b259b437.png)
I also tried 64x32 together with 4 daisy-chained LEDs. 
The option with two parallels doesn't work either:
![image](https://user-images.githubusercontent.com/46962608/56851059-ec815880-690a-11e9-839b-4fd7fe3ce08d.png)

Any help here?

**Comment by ajbowler** [comment]
you should not be updating the utils. You should be using the LED flags when running the software, similar to how you supply `adafruit-hat` to the gpio mapping flag.

Have a look through here: https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard#flags

Reset all the changes you've made to the utils code, as this should not be changed.

The command you probably want here is `sudo python main.py --led-gpiomapping="adafruit-hat" --led-cols=128 --led-rows=64`

Add or remove flags as needed to suit your needs.

**Comment by PHI34Halladay** [comment]
Oh ok, didn't know that - thanks 👍

**Comment by ajbowler** [comment]
Facing the side with the LEDs, left to right as far as number goes. The back of the panels typically has an arrow on it indicating the direction. Consult the RGBMatrix README as it might have more info for you.

**Comment by PHI34Halladay** [comment]
I believe I am too dumb to get this done.
Could somebody with a 128x64 scoreboard send me a picture with his panel and cable setting?
You're also using the w128h64.json file right?

**Comment by ajbowler** [comment]
I am personally not using 128x64, I use 64x32.

Join the slack channel in the README to get faster support on this. For general hardware issues, you are more likely to find support in the RGBMatrix space: https://github.com/hzeller/rpi-rgb-led-matrix
