### ISSUE TITLE
Outdated News Headlines

### ISSUE THREAD

**Issue by msroth** [MLB-LED-Scoreboard/mlb-led-scoreboard#275]
I noticed my news feed is nearly a year out of date. When I checked the URL the scoreboard is using,  mlb.mlb.com/partnerxml/gen/news/rss/was.xml, the data there really is a year old. It looks like the new RSS feed might be www.mlb.com/nationals/feeds/news/rss.xml.

**Comment by swemoney** [comment]
Thanks for the heads up. I updated this in #276 ..
