### ISSUE TITLE
Newbie trying their hand at making this fo the 2020 MLB Season

### ISSUE THREAD

**Issue by RoyalRoostDB24** [MLB-LED-Scoreboard/mlb-led-scoreboard#286]
This is my first time ever doing a project like this and am excited to get this up and running for the upcoming MLB season.  I have never coded before, but have read that this was a good project for beginners.

I'm currently working with the Buster Lite version of the Raspbian OS.

I've tried following the step by step guide in the README file, but keep getting stuck at one point.

I am using the Raspberry Pi Zero W.

When I run, sudo apt-get update, I am getting error messages and and notes that it's failed to fetch certain files.

![unnamed](https://user-images.githubusercontent.com/61659973/76146862-9b7edc80-6064-11ea-843e-29a4a2ba90f7.jpg)

Sorry for the poor quality of the picture.

When I try running sudo apt-get install git python-pip, I am getting the same error messages, just more of them.

I've tried looking through all the comments and files and haven't come across anyone with a similar issue.

Any help would be appreciated.

**Comment by ajbowler** [comment]
This appears to be a Raspberry Pi type issue. You'll have to reach out to folks in the Raspberry Pi community, maybe their forum for help. These issues are for scoreboard-related items so you won't find issues like this here. It appears to be some kind of network issue on your Pi trying to download software in general.
