### ISSUE TITLE
Add Pitcher and Who is At Bat?

### ISSUE THREAD

**Issue by BillLehecka** [MLB-LED-Scoreboard/mlb-led-scoreboard#292]
I'm wondering how hard would it be to add something like who's pitching and who's at bat. For instance, if Jacob deGrom was pitching to Bryce Harper, you could have:

P: 48
AB: 3

How easy would it to be to implement that? Pretty sure it could only be added to a 64x32 or bigger board.

**Comment by ajbowler** [comment]
@BillLehecka this is also #23 

Haven't done any investigation but it depends on what MLB's data can provide us.
