### ISSUE TITLE
Sorting games by start time

### ISSUE THREAD

**Issue by pfightingpolish** [MLB-LED-Scoreboard/mlb-led-scoreboard#298]
Hi all, 

I'm offering this up as a suggested enhancement, but I'm also hoping — hoping — I've already coded the answer. 

One thing that's annoyed me about the code is how the games seemingly come up in no particular order. 

I wanted the games to at least display in order by start time. So I added this code to `data/data.py`: 

1. Before the definition of the `refresh_games` function, I defined a new function I called `get_start_time`. There wasn't much to it. 

```
def get_start_time(self, i):
  return i.game_start_time
```

2. In `refresh_games`, I changed the code that first defines `all_games` to use Python's `sorted` function: 

```all_games = sorted(mlbgame.day(self.year, self.month, self.day), key=self.get_start_time)```

My only fear is how it will handle TBD game start times. I've already encountered a postponed game and it handles it just fine, slotting it into where its original start time was. 

I'm testing it on my board. I'll update if something crashes.

**Comment by twfarley** [comment]
Merged into latest version.
