### ISSUE TITLE
feedparser >= 6.0.0 no longer supports Python 2.7

### ISSUE THREAD

**Issue by ty-porter** [MLB-LED-Scoreboard/mlb-led-scoreboard#299]
The latest version of `feedparser` removes support for Python 2.7 used in the scoreboard:

See [this](https://github.com/kurtmckee/feedparser/commit/ce80fcf2582bbf385ec4d6b958ffdff89a8f0480) commit.

The install script for the scoreboard installs the latest version of `feedparser`:

https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/blob/73f2be8d68e2f56aaebfe4f5e75d88e7d3b37d36/install.sh#L16

---

Short term solution is to supply an upper bound to the `feedparser` version.

```bash
sudo pip install "feedparser<6.0.0"
```

However, there is a larger issue with `pip install` under `sudo`, as it can globally overwrite packages and probably isn't desired. Secondly, no packages have locked versions.

Longer term and possibly better solution is to provide a `requirements.txt` and install them with the normal `pip install` command:

```bash
# Someone with a good scoreboard install can run the following and commit it:
pip freeze > requirements.txt

# install.sh
pip install -r requirements.txt
```

**Comment by pawptart** [comment]
Anyone that's already run the installer and is affected by this issue can uninstall the offending `feedparser` version and replace it with the correct one:

```bash
sudo pip uninstall feedparser
sudo pip install "feedparser<6.0.0"
```
