### ISSUE TITLE
ModuleNotFoundError: No module name 'layout'

### ISSUE THREAD

**Issue by habeckmatt** [MLB-LED-Scoreboard/mlb-led-scoreboard#300]
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from data.scoreboard_config import ScoreboardConfig
  File "/home/pi/mlb-led-scoreboard/data/scoreboard_config.py", line 2, in <module>
    from layout import Layout
ModuleNotFoundError: No module named 'layout'

Any tips on how to resolve this?

**Comment by pawptart** [comment]
This appears to be an issue with compatibility with Python 3.

I currently have a preliminary dev branch going that is aimed at fixing these issues:

https://github.com/pawptart/mlb-led-scoreboard/tree/python3-update

Please note this isn't guaranteed to be bug-free at the moment.
