### ISSUE TITLE
LED flicker and glitching

### ISSUE THREAD

**Issue by MarkBeach6** [MLB-LED-Scoreboard/mlb-led-scoreboard#316]
I have a 64x32 led board with a 5mm pitch and it works fine and I can get the program running, but it often flickers and glitches
[IMG-0343 - Copy.zip](https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/files/6191597/IMG-0343.-.Copy.zip)

**Comment by ty-porter** [comment]
Couple suggestions:

This is generally a hardware issue, so not something we can diagnose over the internet. I'd try re-seating any cables and ensuring there's no cold solder joints (if you've done any modifications). Long data lines can be an issue, so you should replace them with shorter ones if they're too long.

If you're certain the hardware works:

* Ensure you're using the right `--led-gpio-mapping` command line argument
  * https://github.com/hzeller/rpi-rgb-led-matrix/tree/6668ff8b55fcfe5ea36cf22aa48155c9ced177a9#changing-parameters-via-command-line-flags
  
* Try slowing down the GPIO speed
  * https://github.com/hzeller/rpi-rgb-led-matrix/tree/6668ff8b55fcfe5ea36cf22aa48155c9ced177a9#gpio-speed
  
You should check out our [Slack channel](https://mlb-led-scoreboard.herokuapp.com/) for further troubleshooting

**Comment by MarkBeach6** [comment]
I changed the GPIO speed like you said and it seemed to work. Thanks!

**Comment by thomasr05** [comment]
Seems I have the same issue. I'm using a Pi4, Bonnet, 32x32 matrix, 5v 4amp charger and still having no luck.

[Video of the flicker](https://drive.google.com/file/d/1KU58KrPQ6QGxX3uChed7LeGU8vio8X-6/view?usp=sharing)

### What I Have Tried
- I am always using **--led-gpio-mapping="adafruit-hat"** to start the board
- I have disabled the audio in the boot config.txt, so I could make the adjustments.
- Changed out my cables
- Tried setting the GPIO speed from 0-4, so far the default 1 seems to be the best. Despite ADA say 4 for a pi4, it looks completely jacked up.
- Tried dimming the lights nothing really happened to fix it.
- My refresh rate is 230hz... (not sure what the baseline would be, I think 250 decent that I saw)
- Tried adding dtoverlay=w1-gpio gpiopin=19 in the boot config.txt
- I have both my plugged into the pi and the bonnet plugged in (Before just the bonnet gave me low voltage warnings)

### What I haven't tried yet
1. Going headless, although I wouldn't think it would be an issue for a pi4
2. Doing a jumper - https://learn.adafruit.com/adafruit-rgb-matrix-bonnet-for-raspberry-pi/driving-matrices

Any thoughts?

**Comment by pjockey** [comment]
I would do the jumper. Takes couple of minutes to do.

**Comment by thomasr05** [comment]
Did the jumper, the flickering drop a lot but was still there.

I follow the Troubleshooting section and I noticed it made a difference in turning off services. They made the comment you should install the light OS because of software conflicts.
https://github.com/hzeller/rpi-rgb-led-matrix

 I might try headless next.

**Comment by thomasr05** [comment]
I figured out the flickering! Mainly because of me being an idiot. I didn't know how to use flags correctly. I was running the service twice rather than once causing all the issues. 

However, I now see red pixels in the same spots. Any thoughts?

https://drive.google.com/file/d/1bOCfjvIu3aokXYlxejkkCdQr6oq0Q0Rw/view?usp=sharing

`--led-gpio-mapping="adafruit-hat" --led-slowdown-gpio=4 --led-brightness=90`

**Comment by pjockey** [comment]
Place a -pwm after the adafruit-hat.  Don't think you need the quotation marks around adafruit-hat either 

So like --led-gpio-mapping=adafruit-hat-pwm --led-slowdown-gpio=4 --led-brightness=90

**Comment by thomasr05** [comment]
Sadly I tried it and the board goes dark everytime I use  --led-gpio-mapping=adafruit-hat-pwm
I guess I can't even solder two simple pins correclty.... 
Do you think it's because the solder bleeding through the 18pin?
Front - https://ibb.co/jyvLHfy
Back - https://ibb.co/Y3XG0Lq

**Comment by pjockey** [comment]
That looks ok

**Comment by pjockey** [comment]
sudo python main.py --led-gpio-mapping=adafruit-hat-pwm --led-brightness=60 --led-slowdown-gpio=2 --led-rows=32 --led-cols=64

This is my command that works with no flicker or red lines.

**Comment by twfarley** [comment]
Sounds like this was resolved. See https://github.com/hzeller/rpi-rgb-led-matrix for more tips on how to reduce flicker.
