### ISSUE TITLE
64x128 board overlapping

### ISSUE THREAD

**Issue by I3lackshirts** [MLB-LED-Scoreboard/mlb-led-scoreboard#317]
![330AF5EC-923F-4EBA-9B55-A0EFD456222E](https://user-images.githubusercontent.com/81433751/112663525-8ebf5900-8e1e-11eb-91d0-12be7f20d37c.jpeg)x

see the attached picture. Basically what is happening is the first 16 rows are displaying both the first 16 rows and rows 17-32 on top of each other. Same thing is happening for the bottom half. I tried inputting a different led-panel-type and just was getting errors. Anyone run into this before and know what to try?

I am also using the electro dragon board with a Rpi2.

**Comment by twfarley** [comment]
Yeah, I know exactly what's happening. Your HAT doesn't support 64 height. Depending on when you bought it you can modify it to support that much. Share a picture of your HAT and I'll show you what you need to do.

**Comment by I3lackshirts** [comment]
![Uploading A8BDDE32-8D7D-4041-837D-94A5E286F0B4.jpeg…]()

**Comment by I3lackshirts** [comment]
![80E0F0C5-4460-4C3F-A837-F50D5787F1EA](https://user-images.githubusercontent.com/81433751/112681832-da7cfd00-8e34-11eb-821d-a4bb55faead8.jpeg)

**Comment by twfarley** [comment]
Well, I thought I knew but that was when I thought you were using the Adafruit HAT. You'll have to consult the manufacturer of that HAT to find out how to use the E pin for multiplexing.

**Comment by ty-porter** [comment]
Documentation for that adapter is [here](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/adapter/active-3#choose-e-line-for-64x64-panels-with-132-multiplexing).

**Comment by I3lackshirts** [comment]
That was the issue. I connected the E_BUF and P4 pins. Thanks everyone!
