### ISSUE TITLE
Noobie quesstion

### ISSUE THREAD

**Issue by richmyers** [MLB-LED-Scoreboard/mlb-led-scoreboard#318]
To upgrade matrix output to the Enhanced or Plus view.  Exactly what file and where is the supplied code copied into?

**Comment by ty-porter** [comment]
View the READMEs for the following:
https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/tree/master/ledcolors
https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/tree/master/ledcoords

If you're using the layouts from the wiki, note that no additional data is represented is added by changing these files -- it's simply an alternative layout.

**Comment by richmyers** [comment]
Perfect.....thank you.
