### ISSUE TITLE
Lower half of board not blacked out

### ISSUE THREAD

**Issue by richmyers** [MLB-LED-Scoreboard/mlb-led-scoreboard#334]
Lower half of the score board is dimly lit.  Not completely black.  Why are these LED turned on.  The images on the main install page look like this is lit up too.  Would look so much better with the stats in yellow be on a completely black background.  Is there a way to turn these off?

**Comment by twfarley** [comment]
Check the file in ledcolors/scoreboard.json.example. You can modify the default background from 7,14,25 to 0,0,0 to make it black.

**Comment by richmyers** [comment]
BINGO!  Thanks much!
