### ISSUE TITLE
MLB Scoreboard only displaying Weather data

### ISSUE THREAD

**Issue by richmyers** [MLB-LED-Scoreboard/mlb-led-scoreboard#336]
Have two MLB scoreboards.  Power blip took one out.  Rebuilt...but only showing Weather data...which I have configured OpenWeather.  The other board was displaying upcoming game info.....THEN I restarted supervisor on the working board...and now it's only displaying Weather data.  Is the MLB feed down or do I have something wrong?  I have 2 teams and 2 divisions in my config.json file....so not everyone is on an off day.  Thanks in advance.

here is some of the output from the supervisor tail log.  I have not changed any local network config or firewalls.

 Networking Error while refreshing live game status of Royals. 1 retries remaining.
ERROR (13:49:35): URLError: [Errno -3] Temporary failure in name resolution
ERROR (13:49:45): Major networking error while refreshing live game status of Royals
ERROR (13:49:45): Returning team_index of 0 because we ran out of networking retries.
INFO (14:21:11): MLB LED Scoreboard - v4.0.1 (64x32)
INFO (14:21:11): Custom '64x32.json' found. Merging with default reference layout.
INFO (14:21:11): Custom 'scoreboard.json' colors found. Merging with default reference colors.
INFO (19:49:29): MLB LED Scoreboard - v4.0.1 (64x32)
INFO (19:49:29): Custom '64x32.json' found. Merging with default reference layout.

**Comment by pjockey** [comment]
Are you using the version that uses Python2 or Python3?

Have your tried removing or commenting out one of your teams and re-running and see if there is any change?

**Comment by ty-porter** [comment]
@richmyers Have you been able to reproduce this in the last couple days? If it's a one-off I always lean towards an MLB problem.

**Comment by conorlastowka** [comment]
I'm having this same issue  where my board continued to display the weather even though a game was happening. Did you ever discover a fix?

**Comment by twfarley** [comment]
This seems like a config issue. If you're still hitting this reach out on our Slack channel for help.
