### ISSUE TITLE
Board not showing game data

### ISSUE THREAD

**Issue by phonorad** [MLB-LED-Scoreboard/mlb-led-scoreboard#343]
Is anyone having an issue with the board not showing game data, even though there are spring training games in progress?  I have 2 boards, both are showing only the weather page with MLB news scroll bar.  Someone posted what seems to be a similar problem in a previous issue which was posted Aug 2, 2021.  Someone commented there 4 days ago that they are having the same problem as I am seeing.

**Comment by pjockey** [comment]
There is another post in here over the past week

**Comment by ty-porter** [comment]
Spring training games aren't shown in the API this board consumes. There isn't much we can do about it.

**Comment by phonorad** [comment]
OK, thanks, I must have incorrectly remembered seeing spring training games on the board in past years.  Bring on the Regular Season!

**Comment by ty-porter** [comment]
It might have worked in the past, but we don't control that API. That's why there's a disclaimer in the README 😃

**Comment by phonorad** [comment]
Gotcha, no problem, just wanted to make sure that something had not broken!  Thanks for the info and your efforts!
