### ISSUE TITLE
Scoreboard only displaying standings

### ISSUE THREAD

**Issue by MakingSomeWaves** [MLB-LED-Scoreboard/mlb-led-scoreboard#347]
Hey I just today updated to the most recent version, and found that the scoreboard is only displaying the current standings. I've set all of the standing display options in the config file to "false" but it still only shows the standings despite there being games today.

**Comment by WardBrian** [comment]
Can you post your config? Either directly or using something like gist.github.com

**Comment by MakingSomeWaves** [comment]
Solved with a clean install - sorry about that! Thanks for all you do =)

**Comment by twfarley** [comment]
No worries! Thanks for confirming.
