### ISSUE TITLE
Upcoming games don't have AM/PM in the time

### ISSUE THREAD

**Issue by twfarley** [MLB-LED-Scoreboard/mlb-led-scoreboard#357]
Probably a regression from something I changed in the off day renderer for #353.

**Comment by ty-porter** [comment]
Doesn't look like it's new based on `strftime()` implementation: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

Maybe change format to `"%-I %p"`?

**Comment by ty-porter** [comment]
Doesn't look like it's new based on `strftime()` implementation: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

Maybe change format to `"%-I %p"`?

**Comment by twfarley** [comment]
Yeah, the off day renderer has some logic to append the AM or PM.

```
time_format_str = "{}:%M".format(time_format)
    if time_format == "%-I":
        time_format_str += "%p"
```

I'll add this in and test it later tonight.
