### ISSUE TITLE
Scoreboard not switching to game

### ISSUE THREAD

**Issue by richmyers** [MLB-LED-Scoreboard/mlb-led-scoreboard#358]
Scoreboard goes into displaying the standings.  When a favorite team game starts...the scoreboard does to update to the live game.  I have to restart the board to get to live settings.  Attached a couple screenshots of the board and my config.json.  I deleted my weather API...so that's why it looks half configured.  Appreciate the work and support.  Great board!
[config.txt](https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/files/8493066/config.txt)
![IMG20220414192910 1](https://user-images.githubusercontent.com/77252907/163499317-3baf8af7-bc74-408d-82be-abace2b44897.jpg)
![IMG20220414192756](https://user-images.githubusercontent.com/77252907/163499422-26f40ae8-82e1-4129-be2b-fda8aa0167c5.jpg)

**Comment by WardBrian** [comment]
If you look in the example config, there’s a new setting to show the standings when no preferred games are live. It can take a little bit of time during warmup to switch back over. You can turn this off to get the old behavior
