### ISSUE TITLE
Some fonts don't support unicode A4D8 / 42200 (`ꓘ`) for strikeouts looking

### ISSUE THREAD

**Issue by ty-porter** [MLB-LED-Scoreboard/mlb-led-scoreboard#359]
Assets directory has fonts that do support `ꓘ`, currently these are only 4x6 and 5x7.

Example layout files include the following fonts where this glyph is not represented:

- 5x8
- 6x12
- 7x13B
- 9x18B

**Comment by twfarley** [comment]
Looks good. Do we have a place that shows strikeouts? I haven't come across any.

**Comment by ty-porter** [comment]
Yeah, rendering the at-bat can either do a normal K or a backwards K depending on the play:

https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/blob/83f54fce40338ec646ec3530f5c348c55c243266/renderers/games/game.py#L63-L68

**Comment by twfarley** [comment]
Looks good. Pulling in.
