### ISSUE TITLE
Config.json Permission Denied

### ISSUE THREAD

**Issue by rocketgrande** [MLB-LED-Scoreboard/mlb-led-scoreboard#393]
## This issue is a

- [x] Bug Report
- [ ] Feature Request

## Hardware Configuration

- Raspberry Pi Revision (4B+/3B+/Zero/etc.): 3B+
- Operating System: Lite
- Matrix size: 64x32
- Display adapter (HAT/Bonnet/etc.): Adafruit Bonnet
  - Additional information:
- Power source(s): Adafruit 

## Software Configuration

- MLB LED Scoreboard Version: "5.1.1"
- Commands/arguments used to start the scoreboard: sudo python3 main.py --led-gpio-mapping="adafruit-hat"

## Expected behavior
Editing config.json

## Actual behavior
Receive error saying that permission is denied. Can't edit it via nano or via WinSCP.

**Comment by ty-porter** [comment]
In the short term, `chmod` or `chown` it to yourself:

```sh
sudo chmod 777 config.json
```

I think this has to do with RPIs enforcing a user other than `pi` as a default now
