### ISSUE TITLE
Given argument "led-scan-mode" is not set on RGBMatrixOptions

### ISSUE THREAD

**Issue by feram18** [MLB-LED-Scoreboard/mlb-led-scoreboard#396]
## This issue is a

- [X] Bug Report
- [ ] Feature Request

## Software Configuration

- MLB LED Scoreboard Version: `5.1.2`
- Commands/arguments used to start the scoreboard: `--led-scan-mode=1`

## Expected behavior

`RGBMatrixOptions.scan_mode` should be equal to `1`.

## Actual behavior

`RGBMatrixOptions.scan_mode` stays at default `0`.

## Additional Information

Argument `--led-scan-mode` already exists in the ArgumentParser. Just missing a line to set `RGBMatrixOptions`' `scan_mode` property to the given value from argument flag.

**Comment by ty-porter** [comment]
Closed by #397
