### ISSUE TITLE
Center pregame matchup

### ISSUE THREAD

**Issue by ajbowler** [MLB-LED-Scoreboard/mlb-led-scoreboard#40]
Center (as best we can, even numbers and all that) the pregame matchup text depending on matrix width.

![image](https://user-images.githubusercontent.com/6600392/36576876-3140a604-1819-11e8-95f3-054811049ffd.png)

@swemoney has a pretty sweet setup that could use _just a little_ love here.

**Comment by swemoney** [comment]
I doubt the pitcher info will ever be short enough to center. My longer screen just starts scrolling from the edge.

**Comment by ajbowler** [comment]
Yeah I'm talking the teams and the game time

**Comment by flemingjw** [comment]
On the new stretched mode the matchup is centered, but the starters still scroll from the edge

**Comment by ajbowler** [comment]
That is expected, any scrolling text will start from the far right edge and go all the way until the end.

(Well, not yet, they will stop after the refresh, see #30 )
