### ISSUE TITLE
On startup, initializes to weather and stays there...

### ISSUE THREAD

**Issue by mmendelson222** [MLB-LED-Scoreboard/mlb-led-scoreboard#400]
## This issue is a

- [ ] Bug Report
- [ ] Feature Request
- [x] Exploratory question

## Behavior

When I start up my pi, for some reason the connection is not immediately available.  The app initializes to "weather" and stays there. 

A reboot solves the problem, but this presents obvious problems when running headless.  

Before I assume that this is a problem with the app, is there some way to work around this issue?  Perhaps there's a way to increase the timeout, which I'm missing. 

I'll attach my configuration and the debug log. 
[mlb.log](https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/files/9253389/mlb.log)
[config-all.json.txt - removed]()
Thanks.

**Comment by ty-porter** [comment]
You should verify your startup script looks like the one that is in the wiki: https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/wiki

This isn't really an issue with the scoreboard itself, more that the Pi isn't waiting for a connection before running your startup command.

Secondly, the config you uploaded has an API key in it. You should remove the file from the issue as it could be compromised.

**Comment by mmendelson222** [comment]
Thanks @ty-porter, very helpful.
