### ISSUE TITLE
Network error indicator misaligned

### ISSUE THREAD

**Issue by feram18** [MLB-LED-Scoreboard/mlb-led-scoreboard#408]
## This issue is a

- [X] Bug Report
- [ ] Feature Request

## Software Configuration

- MLB LED Scoreboard Version: `5.1.4`

## Expected behavior

Network error indicator should be displayed in the bottom right corner

## Actual behavior

- `128x32` layout has exclamation mark misaligned
- `128x64` layout has both the background and text misaligned

**Comment by ty-porter** [comment]
Screenshots of the issue:

128x32:
![128x32](https://user-images.githubusercontent.com/46663285/188279893-6abe3104-71aa-428d-b7cd-7c745ae113c1.PNG)

128x64
![128x64](https://user-images.githubusercontent.com/46663285/188279894-f07a735d-4ecf-4ef5-a1dd-1336fcb074ff.PNG)

**Comment by ty-porter** [comment]
Addressed by #409
