### ISSUE TITLE
Does this work for Radxa Zero board?  

### ISSUE THREAD

**Issue by washkow** [MLB-LED-Scoreboard/mlb-led-scoreboard#420]
Getting my hands on a pi was been very problematic.  The Radxa website had links to something called Rock Pi, but also Debian Buster, Ubuntu Focal and an Android build.  Can I run this MLB scoreboard using these or should I try to install Rasbian on the Radxa?
Thanks!

**Comment by ty-porter** [comment]
We don't officially support hardware other than Raspberry Pi 3/4 and Zero (with known limitations). It's possible other hardware works, but is not something we can commit to testing at this time.

The operating system is unlikely to be the main issue, but more likely hardware compatibility issues with the driver this uses: https://github.com/hzeller/rpi-rgb-led-matrix
