### ISSUE TITLE
Scoreboard >= v6.3.0 causes games to get "stuck" without rotating

### ISSUE THREAD

**Issue by ty-porter** [MLB-LED-Scoreboard/mlb-led-scoreboard#466]
## This issue is a

- [x] Bug Report
- [ ] Feature Request

## Hardware Configuration

All, as reported in Discord

## Software Configuration

- MLB LED Scoreboard Version: v6.3.0+
- Commands/arguments used to start the scoreboard: N/A

## Expected behavior
Games rotate through live games

## Actual behavior
Games occasionally stop rotating and get "stuck" on a single game.

## Additional Information
Reverting to v6.2.0 resolves, so the change must have been introduced somewhere in v6.3.0

Anyone that needs resolution immediately can checkout a known good version:

```
git checkout 6.2.0

# if using autostart service
sudo service mlb-led-scorebard restart
```

**Comment by pjockey** [comment]
```
git checkout 6.2.0

# if using autostart service
sudo service mlb-led-scorebard restart
```
I have to restart the program everyday as the final scores for the will play forever if I don't. Perhaps something has happened to my config.json file.

**Comment by ty-porter** [comment]
Yes, that is the issue as we have identified it. It is not a config issue to our knowledge

**Comment by WardBrian** [comment]
It wouldn't hurt to share your configs. I haven't had this issue, and I wonder if there is some difference in my config which makes it not noticeable

**Comment by pjockey** [comment]
```
{
  "preferred": {
    "teams": [
      "Blue Jays"
    ],
    "divisions": [
      "AL East",
      "AL Wild Card"
    ]
  },
  "news_ticker": {
    "team_offday": true,
    "always_display": false,
    "preferred_teams": true,
    "traderumors": true,
    "mlb_news": true,
    "countdowns": true,
    "date": true,
    "date_format": "%A, %B %-d",
    "display_no_games_live": false
  },
  "standings": {
    "team_offday": true,
    "mlb_offday": true,
    "always_display": false,
    "display_no_games_live": false
  },
  "rotation": {
    "enabled": true,
    "scroll_until_finished": true,
    "only_preferred": false,
    "only_live": true,
    "rates": {
      "live": 15.0,
      "final": 15.0,
      "pregame": 15.0
    },
    "while_preferred_team_live": {
      "enabled": false,
      "during_inning_breaks": false
    }
  },
  "weather": {
    "apikey": "ef96cea0f9e9806c02181548e66671d2",
    "location": "Cranbrook, CA",
    "metric_units": true
  },
  "time_format": "24h",
  "end_of_day": "01:00",
  "full_team_names": true,
  "short_team_names_for_runs_hits": true,
  "pregame_weather": true,
  "scrolling_speed": 2,
  "debug": false,
  "demo_date": false,
  "preferred_game_update_delay_in_10s_of_seconds": 0
}
```

**Comment by swemoney** [comment]
My config is almost identical aside from the preferred team and standings settings (all sent to false). Also having an issue with rotation just not happening. Last night, it was stuck on the final score to the Minnesota game who's not in my preferred teams or divisions. Didn't rotate to any other final games.

**Comment by swemoney** [comment]
Just to add, I've noticed multiple times since updating to 6.3.0 when the Cubs game was live and it was not staying on the Cubs game. Restarting the scoreboard, I believe, fixes it (when the game is live), and sticks to the Cubs after that.

**Comment by WardBrian** [comment]
My config is different in the following ways I suspect are important:

I have more than one “preferred” team 
I have “only_preferred” set in the rotation.

**Comment by ty-porter** [comment]
```
{
  "preferred": {
    "teams": [
      "Cardinals"
    ],
    "divisions": [
      "NL Central",
      "NL Wild Card"
    ]
  },
  "news_ticker": {
    "team_offday": true,
    "always_display": false,
    "preferred_teams": true,
    "traderumors": true,
    "mlb_news": true,
    "countdowns": true,
    "date": true,
    "date_format": "%A, %B %-d",
    "display_no_games_live": false
  },
  "standings": {
    "team_offday": false,
    "mlb_offday": true,
    "always_display": false,
    "display_no_games_live": true
  },
  "rotation": {
    "enabled": true,
    "scroll_until_finished": true,
    "only_preferred": false,
    "only_live": true,
    "rates": {
      "live": 15.0,
      "final": 15.0,
      "pregame": 15.0
    },
    "while_preferred_team_live": {
      "enabled": false,
      "during_inning_breaks": true
    }
  },
  "weather": {
    "apikey": "YOUR_API_KEY_HERE",
    "location": "Chicago,il,us",
    "metric_units": false
  },
  "time_format": "12h",
  "end_of_day": "00:00",
  "full_team_names": true,
  "short_team_names_for_runs_hits": true,
  "pregame_weather": true,
  "scrolling_speed": 2,
  "debug": true,
  "demo_date": false,
  "preferred_game_update_delay_in_10s_of_seconds": 6
}
```

I have similar config for those 2 keys as @pjockey

**Comment by WardBrian** [comment]
Trying it now with the same config as @ty-porter (except I changed the team to the Tigers, since they have a game that's about to end)

**Comment by WardBrian** [comment]
Okay, I could recreate with 6.3.1 but not with #467, so I think that PR might fix it.
