### ISSUE TITLE
Add option for end of day

### ISSUE THREAD

**Issue by swemoney** [MLB-LED-Scoreboard/mlb-led-scoreboard#52]
Right now, we get the current day based on the current time. An option that could be set to a time before switching to the next day so the scoreboard, after midnight, still rotates through scores from the previous day.

**Comment by ajbowler** [comment]
Should be done after #29 as that will make things easier here

**Comment by swemoney** [comment]
For the time being, I recommend a simple cron job that kills the scoreboard and restarts it at any time you want to roll over to the next day's scores.

**Comment by swemoney** [comment]
Better yet, I've added 2 pages to the [wiki](https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/wiki) for better controlling your scoreboard and accomplishing exactly this.
