### ISSUE TITLE
Create Main Menu

### ISSUE THREAD

**Issue by ajbowler** [MLB-LED-Scoreboard/mlb-led-scoreboard#6]
This would be the new landing page when you spin up the board. Should have a nice graphic and a menu to navigate to either MLB Standings (see #4) or a list of games to pick from (see #7)

Because this requires a sexy graphic, I'm not gonna do it cause I lack the confidence.

**Comment by ajbowler** [comment]
Putting on hold because this will require some keyboard input, see #7

**Comment by craigm26** [comment]
are you planning to have a GUI via HDMI for this? I could do a small python or js server to help control the scoreboard. It'd be nice to control with a smart phone via web browser

**Comment by ajbowler** [comment]
No, ideally there wouldn't be any extra GUI for this, trying to keep the hardware aspect of this down as much as possible. The LED board would show a main menu on startup, then the user can use a keyboard plugged into the Pi without any other hardware to navigate.

**Comment by twfarley** [comment]
What are you thinking of for a graphic for this? I might be able to help out.

**Comment by ajbowler** [comment]
The only thing that I know we _don't_ want is the MLB logo. Legal issues and all that which I'm not interested in getting involved with.

Right now the only criteria I'd like to see is "Games" and "Standings" for the user to pick from, and some kind of title graphic. Tricky part is it all needs to fit on a 32x32 pixel display.

**Comment by craigm26** [comment]
Can the display do a transition animation?  menu then select today’s games (or team or standings), plays animation

I like the idea of keyboard only operation. Use arrow keys and maybe a shutdown command will make a huge difference.

**Comment by ajbowler** [comment]
@craigm26 That's a neat idea to add after the fact, I'll log a separate issue for it after this one gains some traction.

**Comment by ajbowler** [comment]
@craigm26 @twfarley @swemoney I've created a Slack workspace for any general discussions to keep the issues a little cleaner. https://join.slack.com/t/mlb-led-scoreboard/shared_invite/enQtMzE2NjI0MTY3MTI0LTAyZjhlZjk4NWEwZGUyNGM4NGQ4MDM1MDA0NzdhODU0MzRjM2EyMjk2ZDc3YTkyZmI3NDA5N2VkMzExZDQxYmQ

**Comment by craigm26** [comment]
![scoreboardmenuhome](https://user-images.githubusercontent.com/8204366/36334003-14981c6a-132f-11e8-84c8-163123f7aa56.PNG)

**Comment by ajbowler** [comment]
We've committed to the config file route at this point so having another way to do things will be pretty confusing. Closing this issue and other keyboard related ones, at least for now.

**Comment by bryantee** [comment]
I think a way to configure via the web sounds like the ideal solution.

**Comment by twfarley** [comment]
#138 should cover that.
