### ISSUE TITLE
Crash on postponed games

### ISSUE THREAD

**Issue by swemoney** [MLB-LED-Scoreboard/mlb-led-scoreboard#66]
We don't handle postponed games at all. The Cubs game on 5/20/2017 was postponed. Innings is an empty string so it's not processed very well.

**Comment by ajbowler** [comment]
Did you get any meaningful data elsewhere? What's the game status?

**Comment by ajbowler** [comment]
In an easy world the game status would be marked as "Delayed" or "Postponed" and we could easily add some LED rendering for those.

**Comment by swemoney** [comment]
Ya. The game status is Postponed on the game I mentioned. There might be a Delayed status as well. We can probably just make an educated guess and use Delayed for now and handle that until we have live data to test it with.

**Comment by ajbowler** [comment]
Sounds good, should be an easy fix
