### ISSUE TITLE
Add option to display standings on an off day

### ISSUE THREAD

**Issue by alphastanley** [MLB-LED-Scoreboard/mlb-led-scoreboard#73]
Can we embed division standings as an option for off days?  Example move of:

```
standings = mlbgame.standings(datetime.datetime(year, month, day))
division = next(division for division in standings.divisions if division.name == config.preferred_division)
renderers.standings.render(matrix, matrix.CreateFrameCanvas(), division)
```

to the branch logic of:

`if not len(games):`

from main.py.

**Comment by ajbowler** [comment]
This would make a good config option.

- [ ] Add `display_standings_on_offday` config option to `config.json.example`
- [ ] Update README
- [ ] Update code as @alphastanley recommended above

**Comment by ajbowler** [comment]
@alphastanley we have a Slack channel in the README if you're interested in dropping by
