### ISSUE TITLE
Ignore rotate_rates when rotate_games is set to false for pregames/final

### ISSUE THREAD

**Issue by IsThisThingStillOn** [MLB-LED-Scoreboard/mlb-led-scoreboard#82]
RIght now if the scrolling of probable starters takes less than 15 seconds (or whatever duration you chose) with rotate_games set to false, the scoreboard should not start over the scrolling in the middle of the second cycle.

Short video: https://goo.gl/Exx6WW

**Comment by ajbowler** [comment]
Thanks for the report we'll try and get this done for 1.1.0

**Comment by ajbowler** [comment]
The rotate rate will be ignored when rotate_games is set to false, but only for pregames/final. In progress games these will still be honored because:

1. No scrolling text
2. Need to refresh the game data.
