### ISSUE TITLE
Scoreboard showing TBD for probable starters on all Opening Day games and beyond

### ISSUE THREAD

**Issue by IsThisThingStillOn** [MLB-LED-Scoreboard/mlb-led-scoreboard#99]
Installed mlbgame from master branch. It worked fine during Spring Training.

**Comment by flemingjw** [comment]
Mine never worked during spring training and I'd assumed it was some exhibition related glitch.
Still don't work

**Comment by ajbowler** [comment]
From a discussion in Slack it appears that the returned data in the regular season changed causing a conversion error so it defaulted back to TBD. I don't have time to get to it in the next couple days but @swemoney might.

Really need that mlbgame release, too, though.

**Comment by ajbowler** [comment]
Closed with the 1.1.2 release.

**Comment by flemingjw** [comment]
Perhaps I'm missing something here but I still get this behavior. Every pitcher comes up as "TBD". 
I do recall seeing a pitchers name on a postgame screen on the last day of spring training.

**Comment by IsThisThingStillOn** [comment]
You need to install mlbgame from master

**Comment by flemingjw** [comment]
I must not be doing it right but I ran pip uninstall on mlbgame, and reinstalled it. Both times it came back with version 2.4.2 or something. It seems to have fixed it for postgame scrolling, but I still get TBD vs TBD returned for pregame.

**Comment by flemingjw** [comment]
That did the trick @ajbowler 
Thanks guys
